version: 0.2

phases:
  pre_build:
    commands:
      # Usando as variáveis de ambiente em MAIÚSCULAS.
      - echo "Logging in to Amazon ECR in region $REGION..."
      - REPO_URI="$ACCOUNT.dkr.ecr.$REGION.amazonaws.com/$AWS_ECR_REPOSITORY_TARGET_NAME_0"
      
      # Faz o login usando as variáveis de ambiente corretas.
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT.dkr.ecr.$REGION.amazonaws.com

      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Running dotnet publish..."
      - dotnet publish -c Release -o ./build_output MeuSite.csproj

      - echo "Building the Docker image..."
      - docker build -t $REPO_URI:latest .
      - docker tag $REPO_URI:latest $REPO_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing the Docker image to $REPO_URI..."
      - docker push $REPO_URI:latest
      - docker push $REPO_URI:$IMAGE_TAG