version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR in region ${REGION}..."
      - REPO_URI="${ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${AWS_ECR_REPOSITORY_TARGET_NAME_0}"
      - aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Running dotnet publish..."
      - dotnet publish -c Release -o ./build_output MeuSite.csproj
      - echo "Building the Docker image..."
      - docker build -t $REPO_URI:latest .
      - docker tag $REPO_URI:latest $REPO_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing the Docker image to $REPO_URI..."
      - docker push $REPO_URI:latest
      - docker push $REPO_URI:$IMAGE_TAG
      - echo "Creating imagedefinitions.json..."
      - printf '[{"name":"%s","imageUri":"%s"}]' "${CONTAINER_NAME_0}" "${REPO_URI}:${IMAGE_TAG}" > imagedefinitions.json
      - echo "Content of imagedefinitions.json:"
      - cat imagedefinitions.json
      - echo "Extracting port from Port_Mappings_0 variable: ${Port_Mappings_0}"
      - EXTRACTED_PORT=$(echo "${Port_Mappings_0}" | sed -n 's/.*containerPort=\([0-9]*\).*/\1/p')
      - echo "Successfully extracted port: ${EXTRACTED_PORT}"
      - echo "Creating DYNAMIC appspec.yml..."
      - >
        printf 'version: 0.0\nResources:\n  - TargetService:\n      Type: AWS::ECS::Service\n      Properties:\n        TaskDefinition: "%s"\n        LoadBalancerInfo:\n          ContainerName: "%s"\n          ContainerPort: %s\n' \
        "${TASK_DEFINITION_ARN_0}" "${CONTAINER_NAME_0}" "${EXTRACTED_PORT}" > appspec.yml
      - echo "Content of appspec.yml:"
      - cat appspec.yml

# A seção 'artifacts' deve estar aqui, no mesmo nível de 'phases'.
# Ela NÃO PODE estar dentro da seção 'post_build'.
artifacts:
  files:
    - imagedefinitions.json
    - appspec.yml
  discard-paths: yes
